Importing the necessary libraries and functions

In [1]:
import json
import pandas as pd
import numpy as np

Loading the JSON

In [4]:
with open('/content/input_data.json','r') as f:
    data = json.loads(f.read())

Creating a global dictionary to store words and their counts

In [5]:
refined_data = []
global_abst = {}


for i in data:
    temp_dict = dict()
    temp_dict['abstract'] = i['abstract']['_value']
    temp_dict['label'] = i['label']['_value']
    refined_data.append(temp_dict)
    abst = temp_dict['abstract'].split()
    lab = temp_dict['label'].split()
    abst.extend(lab)
    for j in abst:
        if len(j) >=  5:
            x = global_abst.keys()
            if j not in x:
                global_abst[j] = 1
            else:
                global_abst[j] += 1

Sorting the words in descending

In [6]:
global_list = []
for w in sorted(global_abst, key=global_abst.get, reverse=True):
   global_list.append((w))

Creating a list of the 20 most common words

In [7]:
new_list = global_list[:20]
new_list

['should',
 'their',
 'people',
 'would',
 'government',
 'being',
 'which',
 'children',
 'public',
 'Government',
 'British',
 'there',
 'other',
 'years',
 'these',
 'those',
 'health',
 'There',
 'referendum',
 'after']

In [8]:
processed_data = []
for i in refined_data:
    for j in new_list:
        i[j] = 0
    processed_data.append(i)

In [9]:
processed_count = []
for i in processed_data:
    full_text = i['abstract'] + i['label']
    full_words = full_text.split()
    for j in full_words:
        if j in new_list:
            i[j] += 1
            
    processed_count.append(i)

Creating a dataframe with the necessary columns

In [10]:
df = pd.DataFrame(processed_count)
df = df.drop(['abstract','label'], axis=1)
df.insert(0,'petition_id',np.arange(len(df)))

In [11]:
df

,petition_id,should,their,people,would,government,being,which,children,public,...,British,there,other,years,these,those,health,There,referendum,after
0,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1,1,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12382,12382,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12383,12383,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
12384,12384,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12385,12385,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12386,12386,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Converting to CSV

In [12]:
df.to_csv('output2.csv',index=False)